spring:
  application:
    name: ccbs
  datasource:
    url: jdbc:mysql://localhost:3306/career_coach?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ccbs.entity
  configuration:
    map-underscore-to-camel-case: true